# Generated by Django 4.1.1 on 2022-09-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('tel', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('message', models.CharField(max_length=255, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Заявки с формы на странице Контакты',
                'verbose_name_plural': 'Заявки с формы на странице Контакты',
            },
        ),
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
