# Generated by Django 4.1.1 on 2022-09-05 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_block_title', models.CharField(max_length=50, verbose_name='Заголовок блока распродажи')),
                ('action_title', models.CharField(max_length=100, verbose_name='Заголовок акции')),
                ('action_date', models.CharField(max_length=150, verbose_name='Даты проведения')),
                ('action_description', models.TextField(verbose_name='Описани акции')),
                ('action_button', models.CharField(max_length=50, verbose_name='Название кнопки')),
                ('action_image', models.ImageField(upload_to='images/', verbose_name='Изображение акции')),
                ('action_active', models.BooleanField(default=False, verbose_name='Акция активна?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IconBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название иконки')),
                ('icon_class', models.CharField(max_length=50, verbose_name='Класс иконки')),
            ],
            options={
                'verbose_name': 'Иконки',
            },
        ),
        migrations.AlterModelOptions(
            name='index',
            options={'verbose_name': 'Главная'},
        ),
        migrations.AddField(
            model_name='index',
            name='banner_button',
            field=models.CharField(default=1, max_length=50, verbose_name='Кнопка баннера'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='index',
            name='banner_description',
            field=models.CharField(default=1, max_length=150, verbose_name='Описание баннера'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='index',
            name='banner_image',
            field=models.ImageField(default=1, upload_to='images/', verbose_name='Изображение на баннере'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='index',
            name='banner_title',
            field=models.CharField(default=1, max_length=50, verbose_name='Заголовок баннера'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='index',
            name='contact_adress',
            field=models.CharField(default=1, max_length=200, verbose_name='Адрес в подвале'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='index',
            name='contact_email',
            field=models.CharField(default=1, max_length=100, verbose_name='Email в подвале'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='index',
            name='contact_tel',
            field=models.CharField(default=1, max_length=60, verbose_name='Телефон в подвале'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название приемущества')),
                ('description', models.CharField(max_length=200, verbose_name='Описание преимущества')),
                ('benefits', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='benefits_id', to='index.index')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_icon', to='index.iconbenefit')),
            ],
            options={
                'verbose_name': 'Приемущества',
            },
        ),
    ]
