# Generated by Django 4.1.1 on 2022-09-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_action_iconbenefit_alter_index_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'Акция'},
        ),
        migrations.AlterModelOptions(
            name='iconbenefit',
            options={'verbose_name': 'Иконки', 'verbose_name_plural': 'Иконки'},
        ),
        migrations.AddField(
            model_name='action',
            name='action_url',
            field=models.URLField(default=1, max_length=50, verbose_name='Ссылка кнопки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='index',
            name='banner_url',
            field=models.URLField(default=1, max_length=50, verbose_name='Ссылка кнопки'),
            preserve_default=False,
        ),
    ]
