# Generated by Django 4.1.1 on 2022-09-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_action_options_alter_iconbenefit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_url',
            field=models.CharField(max_length=50, verbose_name='Ссылка кнопки'),
        ),
        migrations.AlterField(
            model_name='index',
            name='banner_url',
            field=models.CharField(max_length=50, verbose_name='Ссылка кнопки'),
        ),
    ]
