# Generated by Django 4.1.1 on 2022-09-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_contact_alter_benefit_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='index',
            options={'verbose_name': 'Главная и приемущества'},
        ),
        migrations.AddField(
            model_name='contact',
            name='copywrite',
            field=models.CharField(default=1, max_length=100, verbose_name='Копирайт в подвале'),
            preserve_default=False,
        ),
    ]
