# Generated by Django 4.1.1 on 2022-09-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=60, verbose_name='Заголовок страницы')),
                ('about_description', models.TextField(verbose_name='Описание страницы')),
                ('about_image', models.ImageField(upload_to='images/', verbose_name='Изображение страницы')),
            ],
            options={
                'verbose_name': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='AboutTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100, verbose_name='Имя сотрудника')),
                ('team_post', models.CharField(max_length=100, verbose_name='Должность')),
                ('team_image', models.ImageField(upload_to='images/', verbose_name='Фото сотрудника')),
                ('team_order', models.SmallIntegerField(default=0, verbose_name='Порядок')),
                ('team_index', models.BooleanField(default=False, help_text='Не больше 4 сотрудников для корректного отображения', verbose_name='Выводить сотрудника на главной?')),
                ('team_draft', models.BooleanField(default=False, verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Сотрудники',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
