# Generated by Django 4.1.1 on 2022-09-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_profile_city_alter_profile_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='descr',
            field=models.TextField(default=1, verbose_name='Дополнительная информация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='point',
            field=models.CharField(default=1, max_length=100, verbose_name='Номер дома или офиса'),
            preserve_default=False,
        ),
    ]
