# Generated by Django 4.1.1 on 2022-09-15 20:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=100, verbose_name='Название категории')),
                ('category_url', models.SlugField(max_length=100, unique=True, verbose_name='Ссылка категории')),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категории товара',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_title', models.CharField(max_length=10, verbose_name='Размер')),
            ],
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_title', models.CharField(max_length=150, verbose_name='Название товара')),
                ('catalog_url', models.SlugField(help_text='Должна быть уникальна, формируется после сохранения', max_length=200, unique=True, verbose_name='Ссылка товара')),
                ('catalog_descriptions', models.TextField(verbose_name='Описание товара')),
                ('catalog_price', models.IntegerField(verbose_name='Цена товара')),
                ('catalog_price_old', models.IntegerField(blank=True, verbose_name='Зачеркнутая цена')),
                ('catalog_image', models.ImageField(upload_to='images/catalog/', verbose_name='Изображение товара')),
                ('catalog_new_arrivals', models.BooleanField(default=False, verbose_name='Новое поступление?')),
                ('catalog_date', models.DateTimeField(default=datetime.date.today, help_text='Обновив дату можно поднять товар в очередности', verbose_name='Дата публикации')),
                ('catalog_draft', models.BooleanField(default=True, help_text='Отображение товара', verbose_name='Публикация товара')),
                ('catalog_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category', verbose_name='Категория товара')),
                ('catalog_size', models.ManyToManyField(related_name='size_list', to='catalog.size', verbose_name='Размеры')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
