# Generated by Django 4.1.1 on 2022-09-15 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='catalog_date',
            field=models.DateField(default=datetime.date.today, help_text='Обновив дату можно поднять товар в очередности', verbose_name='Дата публикации'),
        ),
    ]
