# Generated by Django 4.1.1 on 2022-09-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_catalog_catalog_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Размер товара', 'verbose_name_plural': 'Размер товара'},
        ),
        migrations.AddField(
            model_name='size',
            name='size_url',
            field=models.SlugField(default=1, max_length=100, unique=True, verbose_name='Ссылка категории'),
            preserve_default=False,
        ),
    ]
